### ISSUE TITLE
CellXplorer - fantastic use of Mirador for pedagogy

### ISSUE THREAD

**Issue by blalbrit** [IIIF/awesome-iiif#100]
https://courses.edx.org/courses/course-v1:HarvardX+MCB64.1x+2T2016/d16e07a5cec442eeb7cd9dfcb695dce0/

This uses Mirador and annotations as a way of deep-zoom navigation through an online course. Absolutely stunning navigation! Thanks for sharing @rsinghal and please add more info here if that's helpful.

@jronallo - forgive me if this isn't the proper ticketing format. happy to update as necessary.

**Comment by regisrob** [comment]
👍
