### ISSUE TITLE
An Introduction to IIIF by Tom Crane (Digirati)

### ISSUE THREAD

**Issue by srabun** [IIIF/awesome-iiif#105]
http://resources.digirati.com/iiif/an-introduction-to-iiif/

**Comment by regisrob** [comment]
:+1:

**Comment by julsraemy** [comment]
+1

**Comment by srabun** [comment]
Also 2nd part of the primer: http://resources.digirati.com/iiif/an-introduction-to-iiif/wheres-my-model.html

**Comment by kestlund** [comment]
Added in #158
