### ISSUE TITLE
add BSB to Newspapers section

### ISSUE THREAD

**Issue by srabun** [IIIF/awesome-iiif#106]
[6:16]  
Example: https://digipress2.digitale-sammlungen.de/view/bsb00012484_00382_u001/1 
digipress2.digitale-sammlungen.de
digiPress2: Ansicht von Der gerade Weg : Illustrierter Sonntag vom Sonntag dem 22. September 1929
Digitalisierte Anzeige: Der gerade Weg : Illustrierter Sonntag vom Sonntag dem 22. September 1929

[6:17]  
tip for IIIF hackers: If you remove the last two parts from the manifest identifier, you get a manifest for the complete volume that has OCR information via IIIF annotations

[6:18]  
e.g. https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb00012484/manifest 

[6:18]  
https://api.digitale-sammlungen.de/iiif/presentation/bsb00012484/view.html

**Comment by burki** [comment]
For documentation, see https://app.digitale-sammlungen.de/bookshelf/help#entwickler
