### ISSUE TITLE
Press releases

### ISSUE THREAD

**Issue by srabun** [IIIF/awesome-iiif#120]
add press release from the Getty and YCBA

**Comment by julsraemy** [comment]
👍

**Comment by kestlund** [comment]
link?

**Comment by julsraemy** [comment]
They are two links available: 

- The official one from Yale: https://britishart.yale.edu/sites/default/files/files/General%20Press%20Releases/IIIF_FINAL.pdf
- The blog post from the Getty (which redirects to the Yale's website but doesn't give the exact URL to the press release): http://blogs.getty.edu/iris/30000-getty-museum-images-published-iiif/

And two other posts:

- http://mymodernmet.com/iiif-getty-yale-art-collections/ 
- https://enfilade18thc.com/2017/06/06/the-getty-and-ycba-make-100000-images-available-via-iiif/
