### ISSUE TITLE
Add Havard's Biology Cell Annotation Course as a IIIF Awesome

### ISSUE THREAD

**Issue by beaudet** [IIIF/awesome-iiif#124]
https://courses.edx.org/courses/course-v1:HarvardX+MCB64.1x+2T2016/d16e07a5cec442eeb7cd9dfcb695dce0/

**Comment by julsraemy** [comment]
👍

**Comment by jronallo** [comment]
Should we add a STEM heading to put this under? I think we could soon come up with some other examples to add.
