### ISSUE TITLE
consolidate Mirador gems

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#133]
Now that there is an awesome Mirador list, we could reduce the list here to just those Mirador examples that are the gems.

**Comment by jeffreycwitt** [comment]
I'd like to clarify.

http://scta.lombardpress.org is not a mirador instance

It's a different rails application that I've developed (called LombardPress-Web, https://github.com/lombardpress/lombardpress-web) which includes support for IIIF images.

So I would be grateful if it could be listed on the IIIF Awesome List

**Comment by julsraemy** [comment]
Sorry Jeff you're right.

**Comment by jronallo** [comment]
Refer Mirador things to Mirador list and we'll highlight that the Mirador list exists. (agreed in Toronto)
