### ISSUE TITLE
Adding mirador advanced features to awesome list

### ISSUE THREAD

**Issue by saracarl** [IIIF/awesome-iiif#138]
I'd like to see this added to search-within and annotation (for the layers demo):

http://projectmirador.org/demo/advanced_features.html

But I'm really not sure if it belongs, especially if there is a mirador awesome list?

**Comment by jronallo** [comment]
Now that there is a [awesome Mirador](https://github.com/ProjectMirador/mirador-awesome) list, this might be better for that list.
