### ISSUE TITLE
Remove bylines from descriptions?

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#140]
This is a question about curation of the list. I think we should remove bylines from descriptions to shorten them. The descriptions should focus instead on **what** something is and **why** you it is awesome (why you should care to look at it). I would expect that the page or other resource at the other end of the link would have sufficient information on it (or link to information) on who or what institution is behind making the resource available.

I'd like some feedback on this. And though I won't be in Toronto, if we can't come to agreement in this issue, this would be a great topic of discussion for Toronto.

**Comment by srabun** [comment]
👍

**Comment by jronallo** [comment]
I'll draft some language for our guidelines. (agreed in Toronto)

**Comment by srabun** [comment]
4 +1s in Toronto

**Comment by srabun** [comment]
Clean up what we already have so examples are accurate

**Comment by julsraemy** [comment]
+1!
