### ISSUE TITLE
(re)move implementations?

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#141]
I think it may be time to review the decision to include [implementations](https://github.com/IIIF/awesome-iiif#implementations) on the list. There's no good way to scope what goes on here and what doesn't as it is currently defined. There's too much that's missing to be a list of implementations. There's too much included that isn't unique in some way.

Once we have some kind of registry that has responsibility for managing links to implementations, it can definitely be removed at least in its current incarnation. I'm hoping that the discovery group will be able to move on that in the next year.

In the meantime, my proposal is to list any and all implementations in a new `implementations.md` file in this repo. Then the awesome list can link to that. This could either take the form of description it does now or could be a table with a link to the site and columns for which APIs each has implemented. 

If we can do this now, then I think it could help with making decisions about what goes on the list and what doesn't.

**Comment by jronallo** [comment]
Agreed in Toronto that we could start a separate list. The current implementations list is becoming large and really ought to be much longer. Keep the awesome list for the unique things.

**Comment by jronallo** [comment]
Newspapers as an example of showing a short list of examples of implementations.

**Comment by srabun** [comment]
use newsletter to populate implementations list (related to #145 )
