### ISSUE TITLE
Add more vendors that support IIIF in some way

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#144]
I'd like us to consider breaking out vendors and vended products out from open source solutions. If we as a community want to highlight vendors support would we want to call that out in some way through the list? What would be the best way to do that?

**Comment by srabun** [comment]
👍

**Comment by jronallo** [comment]
How to categorize these? Where to put them?

**Comment by jronallo** [comment]
For now we'll add a "Vended Products" section and list them there. LUNA and CONTENTdm could be there.

**Comment by julsraemy** [comment]
+1 to have more vendors on the list

**Comment by srabun** [comment]
- [Zegami](https://zegami.com/international-image-interoperability-framework-iiif-zegami/), a visual data exploration tool, now supports IIIF Image API 2.1 and IIIF Presentation API 2.1.

- [LUNA Imaging](http://www.lunaimaging.com/iiif/) digital collections software supports the Presentation API in LUNA 7.2.5. See [more details about LUNA and IIIF](https://doc.lunaimaging.com/display/V72D/IIIF+in+LUNA) and [demo of LUNA with IIIF in action](https://youtu.be/88IkZ0LSWyI).
