### ISSUE TITLE
Reorder each sub-list to make lightweight recommendations

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#149]
Now many of our sub-lists on the main awesome list are not ordered. We could consider ordering each sub-list as a simple way to make recommendations. For instance while we could continue to list known image servers we could begin the list with the ones we feel are best. Of course what best means is at the discretion of curators and can include considerations like amount of community support, documentation, and whether it gives a good initial impression on adopters. Thoughts on this as a first step towards exercising more judgment in maintaining the list?

**Comment by julsraemy** [comment]
Would we make ordering suggestions on GitHub?
