### ISSUE TITLE
Awesome IIIF is not listed in sindresorhus/awesome

### ISSUE THREAD

**Issue by danhorst** [IIIF/awesome-iiif#15]
I wasn’t sure where it best to put it. Perhaps under [media](https://github.com/sindresorhus/awesome#media)?

---

Also, thanks for the repo! I’m finding it quite useful.

**Comment by jronallo** [comment]
Submitted pull request: https://github.com/sindresorhus/awesome/pull/780

**Comment by srabun** [comment]
To Do's from sindresorhus:

- [ ] check over Awesome IIIF for inconsistent formatting, spelling, and grammar (This includes starting each link description with an uppercase character and ending it with a period ., and consistent naming)

- [ ] change Heading: Awesome IIIF => Awesome International Image Interoperability Framework

- [ ] Include project logo in the top right, like e.g. https://github.com/sindresorhus/awesome-electron (The logo should link to the project website) (The logo should be high-DPI, set it to minimum half the width of the original image)

- [ ] There should be a succinct summary at the top about the project. (You could use the one in this PR)

- [ ] I would like to see some links to community resources (Example: https://github.com/sindresorhus/awesome-electron#community).

- [ ] Maybe include links to videos of talks and other things related.

**Comment by srabun** [comment]
I attempted to do these - see https://github.com/IIIF/awesome-iiif/pull/63

**Comment by jronallo** [comment]
We've made some progress on this. I think we could still improve the consistency of the formatting. For example more closely following the format of the Awesome Electron list: https://github.com/sindresorhus/awesome-electron

**Comment by jronallo** [comment]
We did not fulfill all the requirements to be included in a reasonable time. You can see the relevant ticket here: https://github.com/sindresorhus/awesome/pull/780

Sorry.
