### ISSUE TITLE
STEM examples

### ISSUE THREAD

**Issue by srabun** [IIIF/awesome-iiif#152]
- Cellular imaging demo: https://github.com/imoutsatsos/osdUseCaseHCS 
- Blog from Ioannis Moutsatsos http://imoutsatsos.blogspot.com/2017/04/librarians-and-triple-eye-eff-to-rescue.html 
- Blog from eLife Sciences: https://elifesciences.org/labs/d6044799/dynamically-serving-scientific-images-using-iiif

**Comment by julsraemy** [comment]
+1 to these 3 :)
