### ISSUE TITLE
add links from implementers meeting notes

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#16]
https://docs.google.com/document/d/1WLyNE9fJKYNMXrVcFbmfKGSXxrUrZwiCMv_2s0NYJDs/edit

**Comment by jronallo** [comment]
@rsinghal @aeschylus @edsilv @fractos @dicksonlaw583 @sdellis 
Can you please help me with picking out what links from these notes or other resources for implementers that would be good (and ready) to add to the list? 

Are there other categories we need to add to better capture the work you're doing? For instance I'd like to add ViewDir, but I'm not sure where it belongs.

Add a link and short description here (or submit a pull request) and I can add these. Thank you!

**Comment by rsinghal** [comment]
I think you could link to the ViewDir gitbook: https://viewdir.github.io/.  Perhaps under the Presentation API section? manifesto, manifold, and iiif-tree-component are all described in there and on your list.
