### ISSUE TITLE
3 CIDOC2017 conference presentations

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#161]
https://www.slideshare.net/EmmanuelleGlass/international-image-interoperability-framework-panel-at-cidoc2017-conference

https://www.slideshare.net/EmmanuelleGlass/photo-archives-are-sleeping-beauties-unlocking-images-with-iiif

https://www.slideshare.net/EmmanuelleGlass/iiif-supporting-multidisciplinary-research-at-the-royal-museum-for-central-africa

**Comment by julsraemy** [comment]
👍
