### ISSUE TITLE
Djiiif

### ISSUE THREAD

**Issue by rogerhoward** [IIIF/awesome-iiif#172]
I wrote a Django package `djiiif` for quick and easy integration of Django projects and IIIF (Image API only today). I'd like to add it to the Awesome IIIIF list, but can't settle on a category - perhaps we need a new section, "Framework Integration", or to expand the scope of "CMS Integration"?

https://github.com/rogerhoward/djiiif

Will open a PR against this issue.

**Comment by julsraemy** [comment]
Djiiif was finally added to the shim section
