### ISSUE TITLE
Add Crowdsourcing platforms

### ISSUE THREAD

**Issue by glenrobson** [IIIF/awesome-iiif#176]
This came up on twitter but it would be useful to add a list of IIIF Crowdsourcing platforms and projects.

**Comment by glenrobson** [comment]
Possible examples:
 * https://fromthepage.com/ - example in use: https://library.stanford.edu/blogs/special-collections-unbound/2017/10/archives-launches-transcription-crowdsourcing-project
 * BL and LibCrowds: http://blogs.bl.uk/digital-scholarship/2017/11/crowdsourcing-using-iiif-and-web-annotations.html
 * pelagios project: http://recogito.pelagios.org/
 * NLW and Digirati solution to be released:
   * https://www.llgc.org.uk/blog/?p=14496
   * http://digirati.com/updates/insights/a-crowdsourcing-platform-for-wales/
   * My Rome presentation showing importing a 3rd party collection: https://www.slideshare.net/GlenRobson/nlw-iiif-web-annotation-crowdsourcing-demo

**Comment by anarchivist** [comment]
👍 It seems like we have ample possibilities for a new section dedicated to crowdsourcing.
