### ISSUE TITLE
add browser extension: Open IIIF Manifest Link In Favorite Viewer

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#177]
https://2sc1815j.github.io/Open_IIIF_Manifest_Link_In_Favorite_Viewer/

**Comment by julsraemy** [comment]
👍

**Comment by sdellis** [comment]
👍  This is an excellent (and Accessible) alternative to drag and drop on desktops. Also may cover tablet/mobile use cases (Firefox browsers only). More consistent link patterns are needed to  improve accuracy when auto-identifying manifest links.

**Comment by 2SC1815J** [comment]
I have [a short proposal](https://github.com/2SC1815J/Open_IIIF_Manifest_Link_In_Favorite_Viewer/issues/1) for link patterns. However, we need more discussion.
Once we reach consensus, I would like to implement the patterns in the browser extension.
I would appreciate any comments or suggestions. Thanks in advance.

**Comment by mejackreed** [comment]
Resolved in #233

**Comment by gkenyon** [comment]
👍
