### ISSUE TITLE
Ensure this list of implementations is added

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#188]
Thread from the Code4Lib slack listed some IIIF implementations. We ought to check that they're all listed here.

https://digital.library.villanova.edu/Item/vudl:24299
https://exhibits.stanford.edu/david-rumsey-map-collection/catalog/dq982wy3349
https://spotlight.dlme.clir.org/library/catalog/stanford_pn735pt7303
http://api.wdl.org/  https://labs.loc.gov/lc-for-robots/
https://catalog.princeton.edu/catalog/5430754#view

**Comment by gkenyon** [comment]
👍
