### ISSUE TITLE
Think about api v3

### ISSUE THREAD

**Issue by saracarl** [IIIF/awesome-iiif#194]
So two of the PRs I reviewed today are v3 only -- biiif (#187 ) produces v3 manifests and canvas-panel (#192) is an enhanced viewer component for v3 canvases.  

Canvas panel calls it out in the awesome listing.  biiif does not, but maybe should.

Should we have a v3 section?  (overkill and would be meaningless in short time, perhaps?)  Or does every thing need to have a version specifier?  Or should we just not worry?

**Comment by jronallo** [comment]
Notes from meeting. 
v2 to v3 transition tools.
Questions about "certification".
Each repo includes badge?
The job of the curators should not be to monitor this. 
Some lists do have some classification beyond the major categories.
