### ISSUE TITLE
How to handle translations?

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#197]
Hopefully we'll get more entries for things that have translations. How should be handle translations? Do we add each on its own line? Do we indent them in some way? Do we just include one item with two links?

See for example here:
https://github.com/IIIF/awesome-iiif/pull/169

**Comment by julsraemy** [comment]
In my opinion, only direct translations should be indented.

**Comment by jrhoads** [comment]
I think that including a second link with the translated language as the text would work.
