### ISSUE TITLE
Introducition to IIIF in portuguese

### ISSUE THREAD

**Issue by leogermani** [IIIF/awesome-iiif#236]
https://medium.com/@leogermani/conhecendo-o-iiif-padr%C3%B5es-e-ferramentas-para-publica%C3%A7%C3%A3o-de-imagens-na-web-a62af62a1b36

**Comment by julsraemy** [comment]
👍

**Comment by leogermani** [comment]
Just saw the contributing.md file now and it suggests to create a pull request. Should I do this, addin this link to the reading-viewing.md file?

**Comment by regisrob** [comment]
I do not read portuguese but 👍
