### ISSUE TITLE
Add hosting options?

### ISSUE THREAD

**Issue by glenrobson** [IIIF/awesome-iiif#238]
Should we add options for hosting IIIF images? Candidates I can think of are:

 * Klokan - http://iiifhosting.com/
 * Digirati - https://dlcs.info/
 * Archive.org - Upload image then access from iiif.archivelab.org/iiif/:item_id

Upload Image to archive.org:
 * https://sustainableheritagenetwork.org/digital-heritage/how-upload-content-internet-archive-tutorial

Do archive.org have a collection policy or can anyone upload an image?

**Comment by jronallo** [comment]
An image hosting section is a good idea. Vendors are part of the solution. :+1:
