### ISSUE TITLE
Question: Looking for Content Search Server

### ISSUE THREAD

**Issue by m-art-in** [IIIF/awesome-iiif#252]
I'm looking for a server to host images and fulltext (hOCR). Is there a open source server (Java would be nice). In the  [list](https://github.com/IIIF/awesome-iiif#content-search-api) there is only the Ruby-Server [Ocracoke](https://github.com/NCSU-Libraries/ocracoke).

Thanks for help

**Comment by mbennett-uoe** [comment]
I've a python implementation of IIIF Search (that works of Solr+ALTO files) here: https://github.com/mbennett-uoe/whiiif

There's a newer, more experimental feature version on the "withplugin" branch.
