### ISSUE TITLE
Add Libvips to Image API Libraries

### ISSUE THREAD

**Issue by regisrob** [IIIF/awesome-iiif#286]
The next version of the Libvips library (https://libvips.github.io/libvips/) will come with a level 0 implementation of the Image API (producing level 0 static tiles). 
Seee https://github.com/libvips/libvips/issues/1465

Just have to wait for the release before making a PR...

**Comment by jcupitt** [comment]
Hello, libvips 8.9 is now out and includes `dzsave --layout iiif`.

It's still missing a few features, but it will generate and name all the tiles correctly.

**Comment by regisrob** [comment]
Thank you @jcupitt, this is now merged: https://github.com/IIIF/awesome-iiif#image-api-libraries

**Comment by regisrob** [comment]
Closed by #293
