### ISSUE TITLE
Search and autocomplete on JP2 images in Universal Viewer

### ISSUE THREAD

**Issue by broy-github** [IIIF/awesome-iiif#309]
Hello,

I have the JP2 images and now showing them using IIPServer in Universal Viewer.
Now, I want to implement the search and autocomplete functionality on those JP2 images in Universal Viewer.
I have a very large number of JP2 images.
The search and autocomplete functionality will have to be worked for all text inside the image dynamically.
I am working on .Net application in windows.
Please guide me the implementation process in details.

Thanks

**Comment by broy-github** [comment]
Hello,

Some more details about my application.
I have converted PDF to JP2 images and showing them in Universal Viewer.
I have text with positions info.
I want to implement search with hit highlight on it and want to show on the JP2 image in Universal Viewer.
How can I generate annotations dynamically from it and link it to manifest.json?
Please help me.

Thanks.

**Comment by stephenwf** [comment]
@broy-github The Search specification may be able to help you with the details for what the annotations should look like.
https://iiif.io/api/search/1.0/#use-cases

**Comment by broy-github** [comment]
Sorry, I want some practical info as per my application scenerio/requirement.
Thanks.

**Comment by broy-github** [comment]
Please tell me how can I generate annotations dynamically from text.

**Comment by julsraemy** [comment]
Hi @broy-github, this GitHub repository only lists resources about IIIF. Could you ask your question on IIIF-Discuss (https://groups.google.com/forum/#!forum/iiif-discuss)? Sorry for the late notice.
