### ISSUE TITLE
Add Islandora to the "Digital Asset Management (DAMs) that support IIIF" section

### ISSUE THREAD

**Issue by mjordan** [IIIF/awesome-iiif#315]
Islandora provides partial support for a couple of IIIF APIs: https://islandora.github.io/documentation/user-documentation/iiif/ . Please let me know if you'd like to me open a PR to add it to the "Digital Asset Management (DAMs) that support IIIF" section.

**Comment by regisrob** [comment]
Thanks for suggesting Islandora. Feel free to open a PR to add Islandora the DAM section
