### ISSUE TITLE
Add a link to the IIIF Cookbook

### ISSUE THREAD

**Issue by regisrob** [IIIF/awesome-iiif#340]
Not sure where to add it though... As a new item under Standards ? or in a new sub-section? Or a new paragraph below the APIs list that would give a brief outline of what it is?

https://iiif.io/api/cookbook/

**Comment by hadro** [comment]
I’m inclined to say as a separate line in the intro somewhere, and maybe
also in the same place where we mention the GitHub topics a la the
suggestion in #329 ?
