### ISSUE TITLE
Add IIIF Online Workshop under Tutorials Section

### ISSUE THREAD

**Issue by hadro** [IIIF/awesome-iiif#343]
https://training.iiif.io/iiif-online-workshop/index.html

**Comment by regisrob** [comment]
👍 (it could also be part of the "Official Resources" proposed in #350)

**Comment by julsraemy** [comment]
I propose to actually put https://training.iiif.io/ (or do we rather want the 5 day workshop?) in the "Official Resources".

**Comment by glenrobson** [comment]
The online workshop is the one we are updating. The 5 day one was made for an in person DHSI course we ran in 2019. We may update it for DHSI 2022 but the online  one will be the most up to date for the foreseeable future.

**Comment by julsraemy** [comment]
So better to list https://training.iiif.io/iiif-online-workshop/index.html then :)

**Comment by julsraemy** [comment]
Ping @glenrobson or @hadro

**Comment by hadro** [comment]
Yes, +1 from me
