### ISSUE TITLE
Add Leiden's Islandora IIIF Manifest generator

### ISSUE THREAD

**Issue by hadro** [IIIF/awesome-iiif#366]
https://github.com/LeidenUniversityLibrary/islandora_iiif_manifests

Maybe under [Presentation Libraries](https://github.com/IIIF/awesome-iiif/#presentation-api-libraries)?

**Comment by triplingual** [comment]
[Presentation Manifest Tools](https://github.com/IIIF/awesome-iiif/#presentation-manifest-tools)? Or is it not general enough?
