### ISSUE TITLE
Consider adding pyIIIFpres to manifest generators for 3.0

### ISSUE THREAD

**Issue by hadro** [IIIF/awesome-iiif#367]
Mentioned as useful by Niqui O'Neill, and seems relatively mature: https://github.com/giacomomarchioro/pyIIIFpres

**Comment by martimpassos** [comment]
Was about to open the same issue. For the time being (while prezi3 is still in the works) this is the best available Python alternative I believe. We are using it for generating the imagineRio manifests and it does the job pretty well.

**Comment by hadro** [comment]
Closed via #369 !
