### ISSUE TITLE
https://iiif.link Content State export

### ISSUE THREAD

**Issue by atomotic** [IIIF/awesome-iiif#388]
quick experiment: https://iiif.link
Open a manifest, select a canvas, zoom and pan to a desired detail, and click share. A unique URL will be generated that can be shared over the internet; upon opening the URL the viewer will open at the saved zoom and position. 

example: https://iiif.link/id/1ij66rNas3E7Kh8lt1lXmsAcXQj

more formats:

* https://iiif.link/id/1ij66rNas3E7Kh8lt1lXmsAcXQj/json export a Content State (0.3.0)

* HEAD request returns metadata in http headers  
```
$ curl -I https://iiif.link/id/1ij66rNas3E7Kh8lt1lXmsAcXQj     
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 11 Oct 2020 09:28:41 GMT
Connection: keep-alive
X-Iiif-Canvas: https://images.cogapp.com/iiif/holbein_big_p.tif
X-Iiif-Image: https://images.cogapp.com/iiif/holbein_big_p.tif/15253,18165,7157,3315/,100/0/default.jpg
X-Iiif-Label: Holbein's 'The Ambassadors'
X-Iiif-Manifest: https://storiiies.cogapp.com/holbein/manifest.json
X-Iiif-Page: 0
```

code here, comments are welcome: https://github.com/atomotic/iiif.link  
the viewer frontend is very raw, metadata and label handling could be improved.

next step: i want to implement also Content State _import_, with GET parameter

**Comment by glenrobson** [comment]
Included in IIIF awesome: https://github.com/IIIF/awesome-iiif#import-to-viewers

**Comment by atomotic** [comment]
👍
although is very prototypal and immature, and works only with manifest v2.
I have plan to rewrite from scratch with SvelteKit, iiif-vault and annotorious (for state selection)
