### ISSUE TITLE
http://ghp.wellcomecollection.org/annotation-viewer/quilt/

### ISSUE THREAD

**Issue by jeffreycwitt** [IIIF/awesome-iiif#391]
Sleep stories http://ghp.wellcomecollection.org/annotation-viewer/quilt/ no longer seems live.

**Comment by stephenwf** [comment]
It's still available at this URL: https://wellcometrust.github.io/annotation-viewer/quilt/

**Comment by hadro** [comment]
I've updated this link, thanks for the catch @jeffreycwitt!
