### ISSUE TITLE
Replace DAMs by CMSs (or keep both)?

### ISSUE THREAD

**Issue by martimpassos** [IIIF/awesome-iiif#392]
Some of the software listed in that section are theoretically Collection Management Systems (not be confused with Content Management Systems) rather than Digital Asset Management Systems. Am I nitpicking here?

**Comment by triplingual** [comment]
Even if you are, others might as well. It feels to me like this might be a case where we might succeed by changing the group heading wording in a modest way. Something like "Digital Asset Management Systems and Similar Software"?

**Comment by martimpassos** [comment]
Isn't that too long? Maybe just "Management Software" or "Management Systems"?

**Comment by triplingual** [comment]
It's quite long, for sure. I've proposed opting for descriptiveness over concision. To me, "Management Software" or "... Systems" is insufficiently clear for someone scanning the table of contents. As in "Managing" what?

"Managing Collections and Digital Assets"? Not parallel style to the other entries, but more efficient.
