### ISSUE TITLE
Suggested addition to list: Archive Viewer

### ISSUE THREAD

**Issue by samuelbradshaw** [IIIF/awesome-iiif#426]
[Archive Viewer](https://archiveviewer.org) provides a viewer for scanned images from various archives and repositories. One of the supported formats is the IIIF Presentation API.

Should this be added to the list?

(This is my own hobby project. Is self-promotion of IIIF-related tools allowed?)

Many viewers are confined to a small box on a page, and don't feel native to the web. For this project, I wanted to "break out of the box" with a viewer that feels like a native web page and is responsive to various screen sizes. Images can be selected for printing or sharing, and links are provided to the original source. An example viewer page can be found here:
https://archiveviewer.org/viewer/iiif/https://www.e-rara.ch/i3f/v20/22432962/manifest

You can plug in any IIIF manifest file to test here: https://archiveviewer.org/viewer/iiif

There is also an embedded version of the viewer. An example of the viewer embedded in another site can be found here:
https://singpraises.net/collections/en/songs-of-zion/o-god-the-eternal-father?edition=1908&tab=scanned-page

**Comment by hadro** [comment]
Hi @samuelbradshaw, many thanks for submitting this, and it's totally fine to suggest the addition of a tool that is your own project. 

Can you confirm which version of the IIIF manifests your viewer supports? It looks like only version 2 supported, but let us know (it can be included either way, it will just help us be specific for the listing entry):

Examples:
- version 2: https://archiveviewer.org/viewer/iiif/https://iiif.archive.org/iiif/2/rashodgson68/manifest.json
- version 3: https://archiveviewer.org/viewer/iiif/https://iiif.archive.org/iiif/3/rashodgson68/manifest.json

**Comment by samuelbradshaw** [comment]
Thanks for your reply! Yes, for now it only supports version 2.

**Comment by caitlinPerry** [comment]
Looks good- we'll get it added!
