### ISSUE TITLE
add Annotations section

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#45]
While the Web Annotation work is happening elsewhere these standards and tools are integral to how IIIF works and a great enabler of its interoperability. I would like to consider adding an Annotations section to the list. What are some links that we ought to include to help seed the list?

**Comment by jronallo** [comment]
Annotation servers could be added. What others are there?

https://github.com/azaroth42/MangoServer

**Comment by jbaiter** [comment]
Here's a few I recently found while researching the topic:

- https://github.com/restful-open-annotation/eve-restoa
- https://github.com/glenrobson/SimpleAnnotationServer
- https://github.com/sul-dlss/triannon
- https://github.com/annotationsatharvard/catcha
- https://github.com/CatchPlus/OAS-Open-Annotation-Service / http://www.coda-project.org/index.html%3Fp=125.html

**Comment by glenrobson** [comment]
I believe Catch from Harvard and SimpleAnnotationServer (SAS) are the two servers supported out of the box with Mirador. We're using SAS in a number of transcription projects including a WW1 project to transcribe a Book of Remembrance:

http://hdl.handle.net/10107/4642022

I'm adding support for IIIF search which will hopefully be available above once its live. 

Its also possible to load existing AnnotationLists into SAS so you can started editing the text. Instructions on doing this with an example NLW Newspaper is here [PopulatingAnnotations](../../../glenrobson/SimpleAnnotationServer/blob/master/doc/PopulatingAnnotations.md).

SAS currently supports two back ends Jena by default or Sesame. With the IIIF search I'm looking to add support for SOLR as a backend.

**Comment by srabun** [comment]
SimpleAnnotationServer: https://github.com/glenrobson/SimpleAnnotationServer

**Comment by srabun** [comment]
Digirati recently made available Elucidate: https://github.com/dlcs/elucidate-server

**Comment by srabun** [comment]
MangoServer: https://github.com/azaroth42/MangoServer

**Comment by jronallo** [comment]
Here's the progress I've made so far on a branch to add annotations. Any others I should definitely include? I can add them to that branch and then issue a pull request from it.
https://github.com/IIIF/awesome-iiif/tree/issue-45#annotations

**Comment by srabun** [comment]
@jronallo your section looks good to me so far. Thinking about the audience for this list, in the initial description would it help to clarify how annotations relate to IIIF?

**Comment by jronallo** [comment]
Definitely would be useful to have a better description. I'd suggest we get something basic merged and then improve. I can add an issue to improve the description.
