### ISSUE TITLE
add manifest editing tools

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#46]
There are tools for editing manifests and annotations within a IIIF context that could be added.

**Comment by srabun** [comment]
Manifest editor tool (http://morning-journey-27147.herokuapp.com/#/?_k=agcbor) – tool to create, upload and edit manifests; there is a version installed at the Bodleian (http://iiif.bodleian.ox.ac.uk/manifest-editor/#/?_k=g92i8r)
