### ISSUE TITLE
add iiif-jekyll

### ISSUE THREAD

**Issue by srabun** [IIIF/awesome-iiif#52]
when it's ready...Jekyll-iiif (Peter Binkley):  https://github.com/pbinkley/jekyll-iiif

**Comment by jronallo** [comment]
@srabun Does it seem far enough along now to include? Or still wait?

**Comment by jronallo** [comment]
Considering adding to Image Tools section once https://github.com/IIIF/awesome-iiif/pull/68 is merged.

**Comment by pbinkley** [comment]
It could go in as a work-in-progress - it can be used to generate a usable jekyll site now, but it's clunky. I'm just starting to refactor the IIIF part as a jekyll command plugin. I wrote up some fuller documentation: https://pbinkley.github.io/jekyll-iiif/ .

**Comment by triplingual** [comment]
Is this still an active project, @pbinkley?

**Comment by pbinkley** [comment]
@triplingual no, I've been meaning to archive it. https://github.com/minicomp/wax replaces it.

**Comment by triplingual** [comment]
OK, good to know!
@hadro This can be closed as obsolete.
