### ISSUE TITLE
add Luna implementation

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#57]
Anyone know the best link to provide?

**Comment by regisrob** [comment]
There is this one, but i do not know if it is the most appropriate: http://www.lunaimaging.com/iiif/

**Comment by srabun** [comment]
Links from Drake: 
https://doc.lunaimaging.com/display/V72D/IIIF+in+LUNA
https://doc.lunaimaging.com/display/V72D/What+you+can+do+with+some+IIIF+tools

Standby for link to demo video...

**Comment by srabun** [comment]
see https://github.com/IIIF/awesome-iiif/pull/66
