### ISSUE TITLE
Add other cropping tools

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#65]
IIIF OpenSeadragon Cropping Tool
http://sul-dlss.github.io/iiif-cropper/demo/

IIIF Image Cropper
http://dms-data.stanford.edu/data/iiif-tools/cropper/
https://github.com/lizfischer/iiif-tools

And then UCD has this tool that may just be a demo? http://digital.ucd.ie/crop/?id=ucdlib:33736&pid=ucdlib:33549

**Comment by regisrob** [comment]
See also: 
IIIF Image Cropper for Wikimedia Commons and Wikidata
http://zone47.com/crotos/lab/cropper/
(based on IIIF Image Cropper code by Liz Fischer)

**Comment by jronallo** [comment]
I've added some of these. Let's take up adding any others in a new issue.
