### ISSUE TITLE
more level zero tools

### ISSUE THREAD

**Issue by srabun** [IIIF/awesome-iiif#69]

**Comment by jbaiter** [comment]
demetsiiify, which is already on the list under "Presentation Manifest Tools" could be considered a Level Zero tool. It generates info.json files from multiple resolutions of a single "logical" image that are already hosted as single files. The server then delegates intelligently from the desired IIIF Image API operation to the corresponding image file on the existing server.

**Comment by jronallo** [comment]
If there were a section in the list for Level 0 tools, then it would be good to link to that section in the Guide for IIIF Implementers. 

https://docs.google.com/document/d/1OXxPFrwTDPlx3EfrjEx0Vl5VMy20znfejnvCpmJfmcw/edit#
