### ISSUE TITLE
add An Introduction to the International Image Interoperability Framework

### ISSUE THREAD

**Issue by jronallo** [IIIF/awesome-iiif#77]
https://docs.google.com/document/d/1a2axqqGkjwMYc4rc5hnjM6FMm9WIhKAT3OX6W5ul988/edit

Or is it already on the list?

**Comment by julsraemy** [comment]
👍  (and I don't think it is on the list)

**Comment by tomcrane** [comment]
👍 (predictably...) :) Should I make a PR?

**Comment by jronallo** [comment]
@tomcrane Yes, a pull request would be nice. I just dropped it in here real quick so I wouldn't forget.
