### ISSUE TITLE
Start a new "CMS Integration" section (?)

### ISSUE THREAD

**Issue by regisrob** [IIIF/awesome-iiif#78]
This is a just a proposal for a new section dedicated to CMS plugins related to IIIF. Since I had these links in my Github "stars" I thought it might be useful to share (even though you probably know them already) and potentialy add them to the awesome list... But I did not take the time to test them deeply and I am not really aware of their maturity or if they are still actively maintained (I am quite sure it is the case for UniversalViewer4Omeka but I do not know for the two others). That is why I preferred to open an issue instead of submitting a PR, I think these tools need to be reviewed by the curators of awesome :wink:. I could submit separate PRs if you estimate they are good candidates.

**UniversalViewer4Omeka**
Omeka plugin that implements the IIIF APIs (Image and Presentation) and integrates the UniversalViewer into Omeka.
https://github.com/Daniel-KM/UniversalViewer4Omeka

**Omeka IIIF Plugin**
Omeka plugin that adds support for IIIF APIs into Omeka (IIIF image service used for thumbnails & zoomable viewer, and serves IIIF Presentation API manifests for use in Mirador or other tools).
https://github.com/klokantech/omeka-plugin-IIIF

**Mirador Drupal**
A Drupal module that integrates the Mirador viewer.
https://www.drupal.org/project/mirador

**Comment by jronallo** [comment]
I'm :+1: on adding a new section if there are at least two of these that we can add to it. Sounds like at least one of these can be vouched for. I'm not able to evaluate the others, but they look relatively recent enough to go ahead and add them.

**Comment by edsilv** [comment]
I can vouch for the UniversalViewer4Omeka plugin. Have been using it recently and made a small improvement that I'm planning on creating a PR for at some point.

**Comment by sdellis** [comment]
I don't know what the criteria is for inclusion, but [here's a Drupal 7 module I created](https://www.drupal.org/sandbox/sdellis/2421047) that we are using in production. There are a couple outstanding issues before it can achieve "official module" status. I can't work on them at the moment, but it might be a good starting point for someone who needs to integrate IIIF Images into Drupal 7.

**Comment by regisrob** [comment]
Thx @sdellis, now I remember you talked about it quite a long time ago! If I remember well it is used on Versailles on Paper website: https://rbsc.princeton.edu/versailles/item/878. If the other curators have no objection regarding the experimental status of the module, I am ok to suggest adding it to the list in a forthcoming PR

**Comment by jronallo** [comment]
If it is used in production then it sounds good enough for me. :smile:

@regisrob Could you issue a pull request for the section and include at least UniversalViewer4Omeka and @sdellis' Drupal 7 module since those have been vouched for? Then we're at least advertising that this section could be filled with other good links.

**Comment by regisrob** [comment]
:rocket:

**Comment by hadro** [comment]
This was merged into the list years ago, closing up this issue as part of our August 2023 cleanup effort :)
