### ISSUE TITLE
Implementation - The Frick

### ISSUE THREAD

**Issue by srabun** [IIIF/awesome-iiif#96]
http://digitalcollections.frick.org/digico/#/

**Comment by tristanr-cogapp** [comment]
Is this an implementation? None of the images on the site seem to be using the Image API, nor is there any evidence of Presentation manifests, nor any instructions or visible mention of IIIF at all that I could see.

I'd love to be proved wrong!

**Comment by jbaiter** [comment]
If you click the "add" button on some images and select "Compare" on the bottom of the screen, Mirador will open in a new tab. It looks like the manifests are generated dynamically based on the selection. The image server seems to be a custom implementation (probably Node-based, judging from the response headers) that serves some pretty weird `info.json`, which is not exactly standard-compliant:

```json
{
    "@context": "http://library.stanford.edu/iiif/image-api/1.1/context.json",
    "@id": "http://images.digitalcollections.frick.org:80/media/dzi/c7243003962e3d853f488dc0267997e6",
    "Image": {
        "DisplayRect": null,
        "Format": "jpeg",
        "Overlap": "1",
        "Size": {
            "Height": "5465",
            "Width": "7098"
        },
        "TileSize": "254",
        "Url": "http://images.digitalcollections.frick.org:80/media/dzi/c7243003962e3d853f488dc0267997e6/",
        "xmlns": "http://schemas.microsoft.com/deepzoom/2008"
    },
    "profile": "http://library.stanford.edu/iiif/image-api/2.0/compliance.html#level2"
}
```

Mirador/OSD doesn't seem to mind, though.

**Comment by tristanr-cogapp** [comment]
I stand corrected! I was confused by the fact that all thumbnails aren't IIIF, and the default zoom view uses DZI for OpenSeadragon. 

Glad to see it and happy to have the Frick added to the implementation list.
